### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by opatut** [markdalgleish/serviceworker-loader#3]
Dear @markdalgleish,

there has been an open, uncommented pull request for half a year now. It seems like you lost interest in maintaining this package. Hence, I ask of you to either recommence maintaining this project yourself or to transfer maintainance rights (mostly [npm package ownership](https://docs.npmjs.com/cli/owner)) to somebody else who is willing to maintain it, so all of us can use this module and keep updating it. I think @ConradIrwin or @Autarc might be good candidates for this job :) It's not much to do after all.

Thanks.

**Comment by markdalgleish** [comment]
This was an experimental project that didn't end up getting used in production, but I'm hoping to change that soon. I've recommenced working on this project, and as a result I'll attempt to stay on top of pull requests. However, If you or anyone else are unhappy with how this repo is being managed, please keep in mind that it's MIT licensed, so you're free to take the code and release it under a different name.

**Comment by opatut** [comment]
Thank you for your reply. It just seemed dead to me, since there has been no reply to the merge requests from Jun 17 / Dec 3. If you are interested in keeping this alive, that's great! 

Problem with forking is that we'd have to rename the module unless you transfer npmjs.org module ownership ;) But that won't be an issue now...

FYI: We're using this in production now, it seems to be working fine :) :+1: for you work.
